
create table balance_sheet(
id bigint(20) default 0 ,
publishdate date default 0 ,
reportdate date default 0 ,
curfds bigint(20) default 0 ,
tradfinasset bigint(20) default 0 ,
notesrece bigint(20) default 0 ,
accorece bigint(20) default 0 ,
prep bigint(20) default 0 ,
dividrece bigint(20) default 0 ,
inve bigint(20) default 0 ,
othercurrasse bigint(20) default 0 ,
totcurrasset bigint(20) default 0 ,
longrece bigint(20) default 0 ,
equiinve bigint(20) default 0 ,
fixedassenet bigint(20) default 0 ,
consprog bigint(20) default 0 ,
intaasset bigint(20) default 0 ,
logprepexpe bigint(20) default 0 ,
defetaxasset bigint(20) default 0 ,
othernoncasse bigint(20) default 0 ,
totalnoncassets bigint(20) default 0 ,
totasset bigint(20) default 0 ,
shorttermborr bigint(20) default 0 ,
copeworkersal bigint(20) default 0 ,
taxespaya bigint(20) default 0 ,
intepaya bigint(20) default 0 ,
duenoncliab bigint(20) default 0 ,
totalcurrliab bigint(20) default 0 ,
longborr bigint(20) default 0 ,
longdefeinco bigint(20) default 0 ,
othernoncliabi bigint(20) default 0 ,
totalnoncliab bigint(20) default 0 ,
totliab bigint(20) default 0 ,
paidincapi bigint(20) default 0 ,
capisurp bigint(20) default 0 ,
rese bigint(20) default 0 ,
undiprof bigint(20) default 0 ,
paresharrigh bigint(20) default 0 ,
minysharrigh bigint(20) default 0 ,
righaggr bigint(20) default 0 ,
totliabsharequi bigint(20) default 0
);
